### ISSUE TITLE
Can't auth the bot

### ISSUE THREAD

**Issue by Aerya** [v0idp/Mellow#1]
Hi,

I followed your reqs but can't auth my bot (2FA activated). I'm stucked at [this page](https://i.imgur.com/G537Ba0.png)
So while trying to use the bot he doesnt want my token:
```
[ws] [connection] Connecting to wss://gateway.discord.gg/
[ws] [connection] Connected to gateway wss://gateway.discord.gg/?v=6&compress=zlib-stream&encoding=json
[ws] [connection] Identifying as a new session
[ws] [connection] Setting a heartbeat interval for 41250ms
[ws] [connection] Server closed the WebSocket connection: 4004
[ws] [connection] Clearing heartbeat interval
Disconnected!
[ws] [connection] Tried to identify with an invalid token
```

**Comment by v0idp** [comment]
You need your bot token located in your bot application site, which you will have to enter into your config. the token you input is invalid

**Comment by Aerya** [comment]
Using the Client Secret taken from https://discordapp.com/developers/applications/... doesn't work. I guess its cause I can't auth the bot, right?

**Comment by v0idp** [comment]
Client secret is the wrong token. You have to click "click to reveal" and use that token for your bot. 
![unbenannt](https://user-images.githubusercontent.com/39016303/40584914-fcab12aa-61a9-11e8-9e45-f71babc41bdd.PNG)

**Comment by Aerya** [comment]
Ok, "Sunday, noob day", got the client secret instead of client token...  Thanks for support and the bot!
