### ISSUE TITLE
Ombi web settings erasing after requests

### ISSUE THREAD

**Issue by ctrlaltd1337ed** [v0idp/Mellow#11]
Running Unraid 6.6.6.
Running Ombi Master 3.0.4256.
Pulling "voidp/mellow" repository from Docker Hub, no other tags.
Google Chrome, tried in incognito, it's own window and within Organizrv2.

Bot wasn't working and responded `Unknown command. Use !help or @Request Bot#**** help to view the command list` to all new request attempts so I tried deleting "WebSettings.sqlite3" and re-entering the same information I had before.

After restarting the container, I did a test of `!movie spiderman` and the bot responds as expected, but when I go to click the reaction emoji to confirm, it says `There was an error in your request`.

This is when I go back to Mellow and see that it has deleted all of the Ombi settings I just entered and will clear everything I try to enter after I press Submit.

**Comment by Snipey** [comment]
Could you include the console logs?

**Comment by ctrlaltd1337ed** [comment]
Starting from when I deleted the WebSettings.

https://pastebin.com/L2NzQ5b0

**Comment by Chudz** [comment]
I have exact same issue.
EDIT: I have re-installed fresh and I seem to be able to save my Ombi settings now without them going blank.

**Comment by v0idp** [comment]
do you guys have the persistent folder on the host machine ? also can I see your container configuration ?

**Comment by ctrlaltd1337ed** [comment]
It's all on the appdata folder of my Unraid server.

Docker container: https://i.imgur.com/mBRzoLV.png

**Comment by v0idp** [comment]
@jamesphoto can you try freshly reinstalling mellow to see if that solves the issue ?

**Comment by F13** [comment]
I have the same issue, and a fresh reinstall doesn't seem to fix it. Potentially unrelated, but upon first launch with `yarn start` I receive the following error: `Unhandled rejection Error: SQLITE_ERROR: no such table: bot`. Another run of `yarn start` and the bot seems to start up, although with the error in this issue.

**Comment by v0idp** [comment]
The issue has been identified and will be soon fixed for future versions. Meanwhile if you guys want to fix it for yourself, delete your websettings.db, restart the bot/container and reconfigure the web config.

**Comment by v0idp** [comment]
should be fixed with PR #45
