### ISSUE TITLE
Sonarr does not automatically start searching for added series. 

### ISSUE THREAD

**Issue by myburnemail13** [v0idp/Mellow#112]
I have recently switched the bot to use Sonarr/Radarr instead of Ombi, the bot has no issues adding a series to Sonarr but it will not automatically start searching for it causing me to have to manually go in and fire off the search. Radarr seems to work without issue.

**Comment by Iguana9999phil** [comment]
Is it possible to have an choice option for this for both radarr/sonarr? I'm fine with auto search being default but would like a option to disable it (until admin approval is added) Don't want someone requesting a 32 seasons serie which sonarr starts to search for for example.

**Comment by v0idp** [comment]
Sure I do that

**Comment by v0idp** [comment]
Added both with 859bc2f and e89c94f
