### ISSUE TITLE
Year not added to path

### ISSUE THREAD

**Issue by Iguana9999phil** [v0idp/Mellow#115]
I've set Mellow up to add directly to sonarr and radarr. What I noticed is that all media added by Mellow doesn't contain the year in parentheses in the path. With all the reboots, remakes and plain same titles of movies and series these day I would like to see the year being added as an option.

**Comment by m1dy** [comment]
Yes thats important for me too. 
What worked for me is to remove line 13 `path: radarr.rootfolder + movie.title,` in src/api/helpers/radarr.js and radarr will piece together the folder name by itself and will include the year by default I believe.

**Comment by Iguana9999phil** [comment]
Ah cool, I'm using the docker image though so I can't change it (I can but not seeing a way to restart mellow, can't restart the container or changes reverts) I'll wait until it's pushed in the code.

**Comment by v0idp** [comment]
Fixed in 07aa1bee
