### ISSUE TITLE
HTTPS in HOST URL

### ISSUE THREAD

**Issue by xfouloux** [v0idp/Mellow#12]
Hi,

I am on latest docker version from voidp/mellow

mellow works fine except for tautulli, as it is on https and mellow does not seems to work with it.

&libraries

mellowBOT
@foulou, There was an error in your request.

mellow             | { Error: getaddrinfo ENOTFOUND https https:80
mellow             |     at errnoException (dns.js:55:10)
mellow             |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:26)
mellow             |   code: 'ENOTFOUND',
mellow             |   errno: 'ENOTFOUND',
mellow             |   syscall: 'getaddrinfo',
mellow             |   hostname: 'https',
mellow             |   host: 'https',
mellow             |   port: 80 }

![image](https://user-images.githubusercontent.com/9778409/53918852-48bebd80-40bc-11e9-8427-91e57bde9e43.png)

Can you look into this please ?

Regards

**Comment by v0idp** [comment]
try removing the ``https://`` part and let me know how the result is. also you don't need any port if you use reverse proxy to that subdomain.

**Comment by xfouloux** [comment]
Unfortunatelly, when removing https:// the logs from the docker only says :

mellow             | null

**Comment by v0idp** [comment]
is your website redirecting any http calls to https ?

**Comment by xfouloux** [comment]
no it does not

when you go on http ==> The client sent a plain HTTP request, but this server only speaks HTTPS on this port.

**Comment by v0idp** [comment]
that could be the reason why it's not working. the bot is currently only doing http requests but I was going to add SSL as an option soon to the webconfig. for the time beeing let all http requests redirect to https

**Comment by Alpha5k** [comment]
Resolved in latest build
