### ISSUE TITLE
Discord Disconnect bug

### ISSUE THREAD

**Issue by Motophan** [v0idp/Mellow#126]
https://pastebin.com/xSpuLiEj 

ping 162.159.136.234
PING 162.159.136.234 (162.159.136.234) 56(84) bytes of data.
64 bytes from 162.159.136.234: icmp_seq=1 ttl=55 time=1.42 ms
64 bytes from 162.159.136.234: icmp_seq=2 ttl=55 time=1.39 ms

Whenever my internet connection farts for a second it will crash and will require a container reboot. I am running mellow in a docker container latest develop branch.

**Comment by codetheweb** [comment]
I'm having the same issue.  Have you found any workaround @Motophan besides restarting the container?

**Comment by v0idp** [comment]
pushed a eventlistener to catch all unhandlec exception emitted by the bot. that should stop the crashing and probably automatically reconnect the bot (discord.js should do that automatically) I'll keeo this issue open and wait for your feedbacks.

**Comment by codetheweb** [comment]
Thanks @v0idp, just pulled `:develop` and will let it run overnight to see if it still crashes.

**Comment by codetheweb** [comment]
After running overnight the Discord bot is still online, so it looks like it's fixed.  Thanks for the patch @v0idp!

**Comment by Motophan** [comment]
Bot is still online!

**Comment by v0idp** [comment]
I'll close this. Seems to be fixed.
