### ISSUE TITLE
Bot not showing if Show or Movie is available

### ISSUE THREAD

**Issue by schindlj** [v0idp/Mellow#13]
I have the bot all setup, but when you search with the bot for a movie or TV show, it does not show if the movie or show is already available.  I search Ombi and a shows or movie is listed as available, but the bot does not pickup if it is available until AFTER you request and manually mark it available.

Ombi auto showing movie is available: [https://i.imgur.com/Iut2Jfs.png](url)

Mellow not listing a movie is available: [https://i.imgur.com/ksqK8Yf.png](url)

**Comment by sr8087as** [comment]
Hmm, this is happening to me.  Was working fine yesterday, but I did a reinstall of the bot and now it won't show if films are already available during the bot search.  Ombi is working fine, requests through the bot work fine...but if i request something that I know is already available (even though it is not telling me that it is) it will then download an upgrade of that film.

**Comment by Alpha5k** [comment]
@sr8087as Use the develop branch

**Comment by sr8087as** [comment]
Ok thanks, that worked :)
