### ISSUE TITLE
TV show mismatch on Plex link if show not yet available

### ISSUE THREAD

**Issue by Aerya** [v0idp/Mellow#2]
Hi,

```!tv deep state```
I don't have it yet but the bot tells me its ok
https://i.imgur.com/vTVYGQn.png
```
https://app.plex.tv/desktop#!/server/xxx/details?key=library%2Fmetadata%2F994
```

And it links a movie
https://i.imgur.com/FZ9b4iX.png

**Comment by v0idp** [comment]
did you check sonarr and ombi for the tv show ?

**Comment by Aerya** [comment]
Its ok adding it to Ombi using Mellow or Sonarr/Ombi directly. It's now ok for the Plex link in Mellow, cause I really have the show. The only problem was it linked a movie in Plex as I didn't have the show yet on yesterday.

**Comment by v0idp** [comment]
It seems like there was a problem with your ombi or sonarr, Mellow only retrieves these informations from ombi when you search for a show or movie.  So if it says available and there is a link to another tv show there was probably an error with ombi.

**Comment by Aerya** [comment]
It was ok while searching directly through Sonarr/Ombi. I'll let you know if it happens again.
