### ISSUE TITLE
SQLITE Error on Startup

### ISSUE THREAD

**Issue by v0idp** [v0idp/Mellow#22]
```{ [Error: SQLITE_ERROR: table general already exists] errno: 1, code: 'SQLITE_ERROR' }```
happens on startup since PR #19 @ImDevinC

**Comment by ImDevinC** [comment]
Ahh, I know why this is happening. Since we just moved to migrations but the tables already exist for people who had this, this can happen. I will work on a solution this weekend.

**Comment by ImDevinC** [comment]
I can't get my system into this state to reproduce the error, but can you try this feature branch: https://github.com/ImDevinC/Mellow/tree/feature/optional_migrate. 
This makes the first migration optional, in case users already have the specified tables. This might still have an issue with the `username` field in the `ombi` table, as that came at a later time

**Comment by v0idp** [comment]
should be fixed with PR #45
