### ISSUE TITLE
Mattermost support?

### ISSUE THREAD

**Issue by 12nick12** [v0idp/Mellow#3]
Any chance you'd be able to add mattermost support? I can throw a couple dollars in donations.

**Comment by v0idp** [comment]
What exactly are you looking for feature-wise ?

**Comment by 12nick12** [comment]
Pretty much what this already does, but be compatible with mattermost.

**Comment by ZooShu** [comment]
I think he's looking for a mattermost bot and not a discord bot with sam features

**Comment by v0idp** [comment]
since this is a project dedicated to provide a bot for discord there is currently no effort in creating one for mattermost.

#closed
