### ISSUE TITLE
Bot not working after restart, saying bot token is incorrect but it's not...

### ISSUE THREAD

**Issue by sr8087as** [v0idp/Mellow#34]
i can access the webserver, & i've even tried regenerating the token & changing it again in the webserver, keep getting the following error:

Failed initializing BotClient. Is your token correct?
(node:43380) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'finalize' of null
    at SQLiteProvider.destroy (/path/to/mybot/Mellow-develop/node_modules/discord.js-commando/src/providers/sqlite.js:124:29)
    at BotClient.destroy (/path/to/mybot/Mellow-develop/node_modules/discord.js-commando/src/client.js:171:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:43380) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 14)

**Comment by Brando47** [comment]
getting the exact same issue, hoping it can be fixed soon :)

**Comment by Brando47** [comment]
appears to be an issue with the "develop" tag in docker, switching to "latest" sorted it for me

**Comment by v0idp** [comment]
should be fixed with PR #45
