### ISSUE TITLE
Mellow doesn't actually download anything

### ISSUE THREAD

**Issue by monik3r** [v0idp/Mellow#44]
set up the latest mellow using docker-compose, and was able to send some requests to ombi via discord, but now the bot isn't using the down air reaction/sending requests to ombi. It can successfully search for videos and check the status, but just won't add new requests/react with the down arrow.

My enabled command groups are as follows:
```
Groups
Commands: Enabled
Utility: Disabled
Ombi: Enabled
Sonarr: Enabled
Radarr: Enabled
Tautulli: Disabled
```

Is this a known issue/have any fixes? I haven't seen any similar issues. Great bot otherwise though!

**Comment by asood92** [comment]
having the same issue. 

same command groups as you. for testings sake, disabled sonarr and radarr, still bugs out. 

docker log just shows 

{ error: null, body: '' }

**Comment by Alpha5k** [comment]
Are you receiving an error when you hit the arrow, or is nothing happening at all?

**Comment by asood92** [comment]
"There was an error in your request." was what i was getting. tried building an image from source, in case the build 6 days ago was the issue. used the same appdata. same error.

switched back to the latest build, same error. fixed it by deleting the existing appdata and setting it up again. not sure why that fixed it, but i have both sets of appdata from not working/working if that would help.

**Comment by v0idp** [comment]
> "There was an error in your request." was what i was getting. tried building an image from source, in case the build 6 days ago was the issue. used the same appdata. same error.
> 
> switched back to the latest build, same error. fixed it by deleting the existing appdata and setting it up again. not sure why that fixed it, but i have both sets of appdata from not working/working if that would help.

Send me if possible

**Comment by chrishall09** [comment]
Happened to me to, re-cloning and re-starting fixed it. Tautulli commands not working though. I run the bot through yarn

**Comment by monik3r** [comment]
No arrow appears for me sadly, re-cloning/re-creating the docker container didn't work.

**Comment by v0idp** [comment]
> No arrow appears for me sadly, re-cloning/re-creating the docker container didn't work.

Did you check if a role name is assigned for the request permissions in your web config ? If yes you will need that role name assigned to you in discord to make requests actually.

**Comment by monik3r** [comment]
It's already worked in the past successfully, then didn't work again. No permissions or roles were changed.

**Comment by v0idp** [comment]
should be fixed with PR #45

**Comment by miramusu** [comment]
Unfortunately, I'm having the same issue trying to use it with Sonarr. Everything is fully updated, and a fresh clone was attempted.

Search works fine, but every time a show is searched, the infobox for the selected show appears and the console shows the following error:

`(node:8760) UnhandledPromiseRejectionWarning: TypeError: series.genres.contains is not a function
    at buildSonarrSeries (C:\Mellow\src\api\helpers\sonarr.js:26:23)
    at addSeries (C:\Mellow\src\bots\services\sonarr.js:75:23)
    at C:\Mellow\src\bots\services\sonarr.js:101:20
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:8760) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8760) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by v0idp** [comment]
I see. I probably know why this happens already. Will fix it.
