### ISSUE TITLE
TV requests - "There was an error in your request"

### ISSUE THREAD

**Issue by bobsledboy** [v0idp/Mellow#48]
For some reason even after rebuilding my docker containers I get this error in my container log. My movie request work perfectly with Ombi though.

`
{

  error: Error: Invalid protocol: 192.168.1.8:

      at Request.init (/usr/src/app/node_modules/request/request.js:458:31)

      at new Request (/usr/src/app/node_modules/request/request.js:127:8)

      at request (/usr/src/app/node_modules/request/index.js:53:10)

      at Function.get (/usr/src/app/node_modules/request/index.js:61:12)

      at /usr/src/app/src/util.js:24:17

      at Promise._execute (/usr/src/app/node_modules/bluebird/js/release/debuggability.js:384:9)

      at Promise._resolveFromExecutor (/usr/src/app/node_modules/bluebird/js/release/promise.js:518:18)

      at new Promise (/usr/src/app/node_modules/bluebird/js/release/promise.js:103:10)

      at get (/usr/src/app/src/util.js:23:12)

      at searchTVCommand.run (/usr/src/app/src/commands/ombi/tv.js:154:4)

      at processTicksAndRejections (internal/process/task_queues.js:94:5)

      at async CommandoMessage.run (/usr/src/app/node_modules/discord.js-commando/src/extensions/message.js:235:20)

      at async CommandDispatcher.handleMessage (/usr/src/app/node_modules/discord.js-commando/src/dispatcher.js:143:19),

  body: undefined

}
`

**Comment by v0idp** [comment]
Please specify the branch you are using and provide your settings

Please use the develop branch to fix all these issues.

**Comment by bobsledboy** [comment]
I'm on latest branch, will test the develop branch now.

{
    "AppArmorProfile": "docker-default",
    "Args": [
        "pm2-runtime",
        "src/index.js"
    ],
    "Config": {
        "AttachStderr": false,
        "AttachStdin": false,
        "AttachStdout": false,
        "Cmd": [
            "pm2-runtime",
            "src/index.js"
        ],
        "Domainname": "",
        "Entrypoint": [
            "docker-entrypoint.sh"
        ],
        "Env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "NODE_VERSION=12.14.1",
            "YARN_VERSION=1.21.1",
            "APP=/usr/src/app"
        ],
        "ExposedPorts": {
            "5060/tcp": {}
        },
        "Hostname": "cd729da86fa9",
        "Image": "voidp/mellow:latest",
        "Labels": {
            "maintainer": "void* <voidp@protonmail.com>"
        },
        "OnBuild": null,
        "OpenStdin": false,
        "StdinOnce": false,
        "Tty": false,
        "User": "root",
        "Volumes": null,
        "WorkingDir": "/usr/src/app"
    },
    "Created": "2020-01-15T07:44:34.062087805Z",
    "Driver": "overlay2",
    "ExecIDs": null,
    "GraphDriver": {
        "Data": {
            "LowerDir": "/var/lib/docker/overlay2/f063801d0bae99112fcb80768509a2569954572299e177a2abb1020ec87ce63c-init/diff:/var/lib/docker/overlay2/37346eca85b225b80e9d131bdb76441186b4c46c236f3944c14c167754fd516a/diff:/var/lib/docker/overlay2/5b04490b68bb69e52a17f2d0b071dfd550565f7a2d793d07a4e01dc73ab48464/diff:/var/lib/docker/overlay2/5f2ad6a633ccce49d3451dd768847627e7becc99cca2edadb839ce3415f1eb51/diff:/var/lib/docker/overlay2/77e5733c81dc4c347946a793ed2f9c12518f4f1e259659f724984a2493573a05/diff:/var/lib/docker/overlay2/a17604c85e8d32f42d16c20276a26f3d22077367df03c17d209ca1b77f355448/diff:/var/lib/docker/overlay2/a473aecee635002f333eeec42d2d17761cd2ccd4b79a392f05d2c24a965f0800/diff:/var/lib/docker/overlay2/484d0e3bdd1368e22247f06609fc8fc4eacdce3f92f984834e2f3b8d8b2d9632/diff:/var/lib/docker/overlay2/3a434659c3c11a48f8df4855d84a84af410f07d5d5cf3d27f6cfa629b7743a45/diff:/var/lib/docker/overlay2/7f49df733533189114320129a6da5cc975bb7767b5eea0a48c87ff13cda4ef23/diff:/var/lib/docker/overlay2/c5209c60447d9c9a34fce94ed6f28cc6cea6986adfa8a75ad865b012fc3bac38/diff:/var/lib/docker/overlay2/9667bea6fcfe39a3d186c8b68e6358e63e63bbc492311fa3eed543fa05cd3cd4/diff:/var/lib/docker/overlay2/c699e367962a8b99783a82d36e75e3f7719e22a46404da98593c3ecd8bd01688/diff:/var/lib/docker/overlay2/e5bad1c7553fb6b4f215e1009f0cdc9271213a9a0cc5b812e3943a76d3180d2a/diff:/var/lib/docker/overlay2/19c338eda31071276217c29b4bd350d92382fc24e454569960bdfb61205e749c/diff",
            "MergedDir": "/var/lib/docker/overlay2/f063801d0bae99112fcb80768509a2569954572299e177a2abb1020ec87ce63c/merged",
            "UpperDir": "/var/lib/docker/overlay2/f063801d0bae99112fcb80768509a2569954572299e177a2abb1020ec87ce63c/diff",
            "WorkDir": "/var/lib/docker/overlay2/f063801d0bae99112fcb80768509a2569954572299e177a2abb1020ec87ce63c/work"
        },
        "Name": "overlay2"
    },
    "HostConfig": {
        "AutoRemove": false,
        "Binds": [],
        "BlkioDeviceReadBps": null,
        "BlkioDeviceReadIOps": null,
        "BlkioDeviceWriteBps": null,
        "BlkioDeviceWriteIOps": null,
        "BlkioWeight": 0,
        "BlkioWeightDevice": null,
        "CapAdd": [
            "AUDIT_WRITE",
            "CHOWN",
            "DAC_OVERRIDE",
            "FOWNER",
            "FSETID",
            "KILL",
            "MKNOD",
            "NET_BIND_SERVICE",
            "NET_RAW",
            "SETFCAP",
            "SETGID",
            "SETPCAP",
            "SETUID",
            "SYS_CHROOT"
        ],
        "CapDrop": [
            "AUDIT_CONTROL",
            "BLOCK_SUSPEND",
            "DAC_READ_SEARCH",
            "IPC_LOCK",
            "IPC_OWNER",
            "LEASE",
            "LINUX_IMMUTABLE",
            "MAC_ADMIN",
            "MAC_OVERRIDE",
            "NET_ADMIN",
            "NET_BROADCAST",
            "SYSLOG",
            "SYS_ADMIN",
            "SYS_BOOT",
            "SYS_MODULE",
            "SYS_NICE",
            "SYS_PACCT",
            "SYS_PTRACE",
            "SYS_RAWIO",
            "SYS_RESOURCE",
            "SYS_TIME",
            "SYS_TTY_CONFIG",
            "WAKE_ALARM"
        ],
        "Capabilities": null,
        "Cgroup": "",
        "CgroupParent": "",
        "ConsoleSize": [
            0,
            0
        ],
        "ContainerIDFile": "",
        "CpuCount": 0,
        "CpuPercent": 0,
        "CpuPeriod": 0,
        "CpuQuota": 0,
        "CpuRealtimePeriod": 0,
        "CpuRealtimeRuntime": 0,
        "CpuShares": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "DeviceCgroupRules": null,
        "DeviceRequests": null,
        "Devices": [],
        "Dns": [],
        "DnsOptions": [],
        "DnsSearch": [],
        "ExtraHosts": [],
        "GroupAdd": null,
        "IOMaximumBandwidth": 0,
        "IOMaximumIOps": 0,
        "IpcMode": "private",
        "Isolation": "",
        "KernelMemory": 0,
        "KernelMemoryTCP": 0,
        "Links": null,
        "LogConfig": {
            "Config": {},
            "Type": "json-file"
        },
        "MaskedPaths": [
            "/proc/asound",
            "/proc/acpi",
            "/proc/kcore",
            "/proc/keys",
            "/proc/latency_stats",
            "/proc/timer_list",
            "/proc/timer_stats",
            "/proc/sched_debug",
            "/proc/scsi",
            "/sys/firmware"
        ],
        "Memory": 0,
        "MemoryReservation": 0,
        "MemorySwap": 0,
        "MemorySwappiness": null,
        "NanoCpus": 0,
        "NetworkMode": "bridge",
        "OomKillDisable": false,
        "OomScoreAdj": 0,
        "PidMode": "",
        "PidsLimit": null,
        "PortBindings": {
            "5060/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "5060"
                }
            ]
        },
        "Privileged": false,
        "PublishAllPorts": false,
        "ReadonlyPaths": [
            "/proc/bus",
            "/proc/fs",
            "/proc/irq",
            "/proc/sys",
            "/proc/sysrq-trigger"
        ],
        "ReadonlyRootfs": false,
        "RestartPolicy": {
            "MaximumRetryCount": 0,
            "Name": "unless-stopped"
        },
        "Runtime": "runc",
        "SecurityOpt": null,
        "ShmSize": 67108864,
        "UTSMode": "",
        "Ulimits": null,
        "UsernsMode": "",
        "VolumeDriver": "",
        "VolumesFrom": null
    },
    "HostnamePath": "/var/lib/docker/containers/cd729da86fa9302d5baecf48f5c32f9113ec727d7d35fa292fb48d613626eff2/hostname",
    "HostsPath": "/var/lib/docker/containers/cd729da86fa9302d5baecf48f5c32f9113ec727d7d35fa292fb48d613626eff2/hosts",
    "Id": "cd729da86fa9302d5baecf48f5c32f9113ec727d7d35fa292fb48d613626eff2",
    "Image": "sha256:ac88bca7c001dc5c63db776ec75c39ec2eee90d07627aa6ddb9f770fec58eb88",
    "LogPath": "/var/lib/docker/containers/cd729da86fa9302d5baecf48f5c32f9113ec727d7d35fa292fb48d613626eff2/cd729da86fa9302d5baecf48f5c32f9113ec727d7d35fa292fb48d613626eff2-json.log",
    "MountLabel": "",
    "Mounts": [],
    "Name": "/Mellow",
    "NetworkSettings": {
        "Bridge": "",
        "EndpointID": "b85d967aa9cb10c30a0bb16dabca88ddf9eeb39eb5d3a34d7a02e2226c896e17",
        "Gateway": "172.17.0.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "HairpinMode": false,
        "IPAddress": "172.17.0.11",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "02:42:ac:11:00:0b",
        "Networks": {
            "bridge": {
                "Aliases": null,
                "DriverOpts": null,
                "EndpointID": "b85d967aa9cb10c30a0bb16dabca88ddf9eeb39eb5d3a34d7a02e2226c896e17",
                "Gateway": "172.17.0.1",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "IPAMConfig": {},
                "IPAddress": "172.17.0.11",
                "IPPrefixLen": 16,
                "IPv6Gateway": "",
                "Links": null,
                "MacAddress": "02:42:ac:11:00:0b",
                "NetworkID": "b59c06daa3e62e1d82155d9c93f97c30db4f5647cc380b811f820861ba43817d"
            }
        },
        "Ports": {
            "5060/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "5060"
                }
            ]
        },
        "SandboxID": "fd482680eec7c345636b086bc2193561371146fdf654212f73ba0d68ca4bab41",
        "SandboxKey": "/var/run/docker/netns/fd482680eec7",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null
    },
    "Path": "docker-entrypoint.sh",
    "Platform": "linux",
    "Portainer": {
        "ResourceControl": {
            "Id": 17,
            "ResourceId": "cd729da86fa9302d5baecf48f5c32f9113ec727d7d35fa292fb48d613626eff2",
            "SubResourceIds": [],
            "Type": 1,
            "UserAccesses": [
                {
                    "UserId": 0,
                    "AccessLevel": 1
                }
            ],
            "TeamAccesses": [],
            "Public": false,
            "AdministratorsOnly": false,
            "System": false
        }
    },
    "ProcessLabel": "",
    "ResolvConfPath": "/var/lib/docker/containers/cd729da86fa9302d5baecf48f5c32f9113ec727d7d35fa292fb48d613626eff2/resolv.conf",
    "RestartCount": 0,
    "State": {
        "Dead": false,
        "Error": "",
        "ExitCode": 0,
        "FinishedAt": "2020-01-15T08:31:08.892347159Z",
        "OOMKilled": false,
        "Paused": false,
        "Pid": 3236,
        "Restarting": false,
        "Running": true,
        "StartedAt": "2020-01-15T08:32:23.415296116Z",
        "Status": "running"
    }
}

**Comment by bobsledboy** [comment]
Develop branch fixed everything thanks for your help.
