### ISSUE TITLE
Do not auto-approve requests 

### ISSUE THREAD

**Issue by sbcrumb** [v0idp/Mellow#5]
I would like to not have the mellow bot auto-approve requests.
I would like them to still need admin approval. Is there a way to accomplish this?

Or allow us to specify a user from Ombi, Say a Discord user, and apply limits to the account.

**Comment by goldenpipes** [comment]
+1

**Comment by goldenpipes** [comment]
Currently mellow uses the Api "user" dilo do stuff. Ideally you could edit the mellow script to use a different user instead. But I don't know what that entails.

**Comment by v0idp** [comment]
The API user has all its requests auto approved by ombi. Sadly I can't change it on my end.
