### ISSUE TITLE
Can't specify ApiAlias

### ISSUE THREAD

**Issue by BlackVQ35HR** [v0idp/Mellow#7]
Where did you specify an ApiAlias? At the moment if you request anything it's approved because the Api for Ombi has admin permissions. If I can change the ApiAlias, any request gets does not get auto approved and must wait till it gets approved. 

In Ombi if you specify an ApiAlias it uses a user's permissions to prevent auto approval. See the link for more info.
https://github.com/tidusjar/Ombi/wiki/Api-Information

Thank you,

**Comment by v0idp** [comment]
If you want custom permissions switch to the develop branch. It's also available as a tag on dockerhub. You will need the newest ombi develop version to make it work. Also make sure to delete the websettings database before upgrading. You can then set the ombi user in your websettings and have permissions set for that in the ombi settings. 

The API alias is only used to display the discord username to ombi.

**Comment by v0idp** [comment]
If you want custom permissions switch to the develop branch. It's also available as a tag on dockerhub. You will need the newest ombi develop version to make it work. Also make sure to delete the websettings database before upgrading. You can then set the ombi user in your websettings and have permissions set for that in the ombi settings.

**Comment by BlackVQ35HR** [comment]
I will try that. Thanks.

**Comment by v0idp** [comment]
Since there is no follow up I will close this. If you have any issues feel free to reopen
